--EXPLORATORY DATA ANALYSIS--
--1.EXPLORE OBJECTS IN DB
SELECT * FROM INFORMATION_SCHEMA.TABLES
--2.EXPLORE COLUMNS IN DB
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME= 'DIM_CUSTOMERS'
--3.EXPLOE DIMENSIONS
--IDENTIFY UNIQUE VALUES (CATEGORIES) IN EACH DIM
--RECOGNIZE HOW DATA MIGHT BE GROUPED OR SEGMENTED (DISTINCT)
--4.EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM.
SELECT DISTINCT COUNTRY FROM GOLD.DIM_CUSTOMERS
--5.EXPLORE ALL CATEGORIES & SUBCATEGORIES & PRODUCTS
--TO DETECT LEVEL OF GRANUALITY
SELECT DISTINCT CATEGORY,SUBCATEGORY,PRODUCT_NAME  
FROM GOLD.DIM_PRODUCTS
ORDER BY 1,2,3
--6.EXPLORE DATE COLUMNS
--IDENTIFY THE BOUNDARIES (EARLIEST&LATEST)
--UNDERSTAND SCOPE OF DATA & IT'S TIMESPAN 
--USE MIN/MAX FUNCTIONS
SELECT MIN(ORDER_DATE),
MAX(ORDER_DATE),
DATEDIFF(YEAR,MIN(ORDER_DATE),MAX(ORDER_DATE))
FROM GOLD.FACT_SALES
--FIND YOUNGEST & OLDEST CUSTOMER 
SELECT 
MIN(BIRTHDATE) AS OLDEST_BIRTHDATE,
MAX(BIRTHDATE) AS YOUNGEST_BIRTHDATE
FROM GOLD.DIM_CUSTOMERS

--7.MEASURE EXPLORATION 
--CALCULATE KEYMETRIC OF BUSINESS (BIG NUMBERS)
--HIGHEST,LOWEST LEVE OF AGGREGATION
--======================
--1.FIND TOTAL SALES
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES 
FROM GOLD.FACT_SALES
--2.HOW MANY ITEMS ARE SOLD
SELECT SUM (QUANTITY) AS TOTAL_SALES 
FROM GOLD.FACT_SALES
--3.AVERAGE SELLING PRICE 
SELECT AVG (PRICE) AS AVG_PRICE 
FROM GOLD.FACT_SALES
--4.TOTAL NUMBER OF ORDERS 
SELECT COUNT (DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS 
FROM GOLD.FACT_SALES
--5.FIND TOTAL NO. OF PRODUCTS
SELECT COUNT(PRODUCT_KEY) AS TOTAL_PRODUCTS 
FROM GOLD.DIM_PRODUCTS
--6.TOTAL CUSTOMERS NO. (CUST TABLE)
SELECT COUNT(CUSTOMER_KEY) AS TOTAL CUSTOMERS
FROM GOLD.DIM_CUSTOMERS
--7.TOTAL CUSTOMERS WHO PLACED ORDER (FACT TABLE)
SELECT COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL CUSTOMERS
FROM GOLD.FACT_SALES
--=======================
--REPORT
--=======================
SELECT 'Total Sales'                   
AS MEASURE_NAME, SUM(SALES_AMOUNT)              
AS MEASURE_VALUE FROM GOLD.FACT_SALES
UNION ALL
SELECT 'Total Items Sold'              
AS MEASURE_NAME, SUM(QUANTITY)                  
AS MEASURE_VALUE FROM GOLD.FACT_SALES
UNION ALL
SELECT 'Average Selling Price'          
AS MEASURE_NAME, AVG(PRICE)                     
AS MEASURE_VALUE FROM GOLD.FACT_SALES
UNION ALL
SELECT 'Total Orders'                  
AS MEASURE_NAME, COUNT(DISTINCT ORDER_NUMBER)   
AS MEASURE_VALUE FROM GOLD.FACT_SALES
UNION ALL
SELECT 'Total Products'                 
AS MEASURE_NAME, COUNT(PRODUCT_KEY)             
AS MEASURE_VALUE FROM GOLD.DIM_PRODUCTS
UNION ALL
SELECT 'Total Customers'                
AS MEASURE_NAME, COUNT(CUSTOMER_KEY)            
AS MEASURE_VALUE FROM GOLD.DIM_CUSTOMERS
UNION ALL
SELECT 'Customers Who Placed Orders'    
AS MEASURE_NAME, COUNT(DISTINCT CUSTOMER_KEY)   
AS MEASURE_VALUE FROM GOLD.FACT_SALES;
--===================
--===================
--MAGNITUDE ANALYSIS
--===================
--===================
--COMPARE MEASURE VALUES BY CATEGORIES TO HELP 
--UNDERSTANDING IMPORTANCE OF DIFFERENT CATEGORIES
--[MEASURE] BY [DIMENSION]
--====================
-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
--===========================
/*
===============================================================================
Ranking Analysis
===============================================================================
Purpose:
    - To rank items (e.g., products, customers) based on performance or other metrics.
    - To identify top performers or laggards.

SQL Functions Used:
    - Window Ranking Functions: RANK(), DENSE_RANK(), ROW_NUMBER(), TOP
    - Clauses: GROUP BY, ORDER BY
===============================================================================
*/

-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- Complex but Flexibly Ranking Using Window Functions
SELECT *
FROM (
    SELECT
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key
    GROUP BY p.product_name
) AS ranked_products
WHERE rank_products <= 5;

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ;








